DASH device init
plvisiondevs/SAI-Challenger.OCP pull request #5
Opened 2022-08-26 06:28 UTC by maksymhedeon

Signed-off-by: Maksym Hedeon <maksym.hedeon@plvision.eu>

2022-08-30 10:44 UTC, anton7811 requested changes

2022-08-30 10:44 UTC, anton7811 commented on common/sai_dpu.py
> +            status, data = self.get(self.dot1q_br_oid, ["SAI_BRIDGE_ATTR_PORT_LIST", "1:oid:0x0"], False)
Let's comment out SAI_BRIDGE_* operations for now. 99.9% that this API won't be present in DASH.
The same is most probably about SAI_VLAN_*

But SAI_SWITCH has to be there.

2022-08-31 10:34 UTC, elchupanebrej commented on setups/sai_dpu_client_server.json
>      "alias": "dash",
This config is part of test environment so has to be stored in DASH repository

2022-08-31 10:34 UTC, elchupanebrej commented on setups/sai_dpu_client_server.json
>      "alias": "dash",
@anton7811

2022-09-05 08:55 UTC, closed without merging